### PR TITLE
Crash scan

### PR DESCRIPTION
**Pull request by Aaronstar-McClure**
### Description of the Change

This is an attempt to allow the bot to scan atl pasts for common crash causes

### Testing

I try to test each section as I write it, but as this is my first time writing, i recommend thorough testing and code checking.

### Related Issues

#20

### CODE REVIEW

**Comment by RyanTheAllmighty** [comment]
Is this ready to review? If so hit the `Ready for review` button and can take a look :)

**Comment by Aaronstar-McClure** [comment]
O, no, im still working on lots of stuff...

**Comment by RyanTheAllmighty** [comment]
@Aaronstar-McClure any update on this?

**Comment by Aaronstar-McClure** [comment]
oops

**Comment by Aaronstar-McClure** [comment]
i just accidentally messed a bunch of stuff up, so i am going to remake this pr

**Pull request closed without merging**
